/**
 * Generated by scripts/process-photos.mjs. Do not edit by hand.
 *
 * Intrinsic size of the largest derivative of each photograph, plus the widths
 * that exist on disk, so markup can reserve space and build a srcset without
 * guessing.
 */
export type PhotoFile = {
  width: number;
  height: number;
  widths: number[];
};

export const photoFiles = {
  "antelope-canyon": { width: 1400, height: 1050, widths: [480, 800, 1400] },
  "balloon-flame": { width: 788, height: 1400, widths: [270, 450, 788] },
  "chicago-river": { width: 825, height: 1100, widths: [300, 540, 825] },
  "composite-study": { width: 1400, height: 700, widths: [560, 900, 1400] },
  "dallas-bridge": { width: 1400, height: 1050, widths: [480, 800, 1400] },
  "emerald-lake": { width: 1400, height: 1050, widths: [480, 800, 1400] },
  "golden-gate": { width: 1400, height: 1050, widths: [480, 800, 1400] },
  "headshot": { width: 733, height: 1100, widths: [267, 480, 733] },
  "hollywood-sign": { width: 825, height: 1100, widths: [300, 540, 825] },
  "la-skyline": { width: 1400, height: 1050, widths: [480, 800, 1400] },
  "overlook": { width: 2000, height: 924, widths: [640, 1024, 1600, 2000] },
  "redwood-road": { width: 1050, height: 1400, widths: [360, 600, 1050] },
  "sf-wheel": { width: 1050, height: 1400, widths: [360, 600, 1050] },
  "sunset-dock": { width: 1050, height: 1400, widths: [420, 675, 1050] },
  "train-platform": { width: 825, height: 1100, widths: [300, 540, 825] },
  "undergrad-computer-block": { width: 733, height: 1100, widths: [267, 480, 733] },
  "usc-steps-of-troy": { width: 825, height: 1100, widths: [300, 540, 825] },
  "usc-traveler": { width: 825, height: 1100, widths: [300, 540, 825] },
  "water-wall": { width: 897, height: 1400, widths: [359, 576, 897] },
  "waterfall-hike": { width: 1050, height: 1400, widths: [360, 600, 1050] },
  "wind-turbine": { width: 788, height: 1400, widths: [270, 450, 788] },
  "wing-city-lights": { width: 1050, height: 1400, widths: [360, 600, 1050] },
} as const satisfies Record<string, PhotoFile>;

export type PhotoSlug = keyof typeof photoFiles;
