/**
 * Generated by scripts/process-photos.mjs. Do not edit by hand.
 *
 * Intrinsic size of the largest derivative of each file, plus the widths that
 * exist on disk, so markup can reserve space and build a srcset without
 * guessing.
 *
 * Photographs and artwork are listed separately, and stay separate all the way
 * up through src/data/photos.ts and src/data/artwork.ts. A photograph is a
 * record of something; an illustration is a made thing. Only one of them can be
 * offered as evidence.
 */
export type AssetFile = {
  width: number;
  height: number;
  widths: number[];
};

/** Photographs, as taken. */
export const photoFiles = {
  "antelope-canyon": { width: 1400, height: 1050, widths: [480, 800, 1400] },
  "balloon-flame": { width: 788, height: 1400, widths: [270, 450, 788] },
  "chicago-river": { width: 825, height: 1100, widths: [300, 540, 825] },
  "dallas-bridge": { width: 1400, height: 1050, widths: [480, 800, 1400] },
  "emerald-lake": { width: 1400, height: 1050, widths: [480, 800, 1400] },
  "golden-gate": { width: 1800, height: 1350, widths: [560, 900, 1400, 1800] },
  "headshot": { width: 733, height: 1100, widths: [267, 480, 733] },
  "hollywood-sign": { width: 825, height: 1100, widths: [300, 540, 825] },
  "la-skyline": { width: 1400, height: 1050, widths: [480, 800, 1400] },
  "overlook": { width: 2000, height: 924, widths: [640, 1024, 1600, 2000] },
  "redwood-road": { width: 1050, height: 1400, widths: [360, 600, 1050] },
  "sf-wheel": { width: 1050, height: 1400, widths: [360, 600, 1050] },
  "sunset-dock": { width: 1152, height: 1536, widths: [420, 675, 1050, 1152] },
  "train-platform": { width: 825, height: 1100, widths: [300, 540, 825] },
  "undergrad-computer-block": { width: 733, height: 1100, widths: [267, 480, 733] },
  "usc-steps-of-troy": { width: 825, height: 1100, widths: [300, 540, 825] },
  "usc-traveler": { width: 825, height: 1100, widths: [300, 540, 825] },
  "water-wall": { width: 1153, height: 1800, widths: [359, 576, 897, 1153] },
  "waterfall-hike": { width: 1050, height: 1400, widths: [360, 600, 1050] },
  "wind-turbine": { width: 788, height: 1400, widths: [270, 450, 788] },
  "wing-city-lights": { width: 1050, height: 1400, widths: [360, 600, 1050] },
} as const satisfies Record<string, AssetFile>;

/** Illustrations, built to the design. */
export const artFiles = {
  "contour-ridge": { width: 1800, height: 1350, widths: [560, 900, 1400, 1800] },
  "horizon-vista": { width: 2560, height: 1440, widths: [640, 1024, 1600, 2048, 2560] },
  "system-graph": { width: 2560, height: 1440, widths: [640, 1024, 1600, 2048, 2560] },
} as const satisfies Record<string, AssetFile>;

export type PhotoSlug = keyof typeof photoFiles;
export type ArtSlug = keyof typeof artFiles;

/** Anything the <Photo> component can render, whichever kind it is. */
export const assetFiles = { ...photoFiles, ...artFiles };
export type AssetSlug = PhotoSlug | ArtSlug;
